"""アプリ全体で参照する定数。"""

from __future__ import annotations

APP_NAME = "LivelyRec"
DATA_DIR_NAME = "livelyrec_data"

DEFAULT_BUSINESS_DAY_ROLLOVER_HOUR = 6
DEFAULT_OBS_HOST = "127.0.0.1"
DEFAULT_OBS_PORT = 4455
DEFAULT_WS_HOST = "127.0.0.1"
DEFAULT_WS_PORT = 14514
DEFAULT_FPS = 8

SCREEN_BASE_WIDTH = 1366
SCREEN_BASE_HEIGHT = 768

SCHEMA_VERSION = 1
WS_SCHEMA_VERSION = "v1"
